---
title: "Homework 7"
format: html
---


```{r}
library(dplyr)
library(tidyverse)
data(iris)
str(iris)
class(iris)
```

1 There are 5 different variables and 150 observations
2 There are 56 observations and 3 variables
```{r}
iris1 <- iris%>%
  filter(Species != "setosa" & Sepal.Length > 6 & Sepal.Width > 2.5)
str(iris1)
```

there are 56 observations and 5 variables

# Question 3
```{r}
iris2 <- iris1%>%
  select(Species, Sepal.Length, Sepal.Width)
str(iris2)
```

there are 56 observations and 3 variables

# Question 4
```{r}
iris3 <- iris2%>%
  arrange(desc(Sepal.Length))
head(iris3)
```

# Question 5
```{r}
iris4 <- iris3%>%
  mutate(iris3, Sepal.Area=Sepal.Length*Sepal.Width)
str(iris4)
```

theres 56 observations and 4 variables

# Question 6
```{r}
iris5 <- iris4%>%
  summarise(avg.Sepal.Width = mean(Sepal.Width), avg.Sepal.Length = mean(Sepal.Length),
  avg.Sepal.Area = mean(Sepal.Area), samp.size = n())
print(iris5)
```

# Question 7
```{r}
iris6 <- iris4%>%
  group_by(Species)%>%
  summarise(Average.Sepal.Length = mean(Sepal.Length), Average.Sepal.Width = mean(Sepal.Width),
  Average.Sepal.Area = mean(Sepal.Area), samp.size = n())
print(iris6)
```

# Question 8
```{r}
irisFinal <- iris%>%
  filter(Species != "setosa" & Sepal.Length > 6, Sepal.Width > 2.5)%>%
  select(Species, Sepal.Length, Sepal.Width)%>%
  arrange(desc(Sepal.Length))%>%
  mutate(Sepal.Area = Sepal.Length*Sepal.Width)%>%
  group_by(Species)%>%
  summarise(Average.Sepal.Length = mean(Sepal.Length), Average.Sepal.Width = mean(Sepal.Width),
  Average.Sepal.Area = mean(Sepal.Area), samp.size = n())
print(irisFinal)
str(irisFinal)
```

# Question 9
```{r}
irisLong <- iris%>%
  pivot_longer(cols=c(Sepal.Length, Sepal.Width, Petal.Length, Petal.Width),
  names_to="Measure", values_to="Value")
str(irisLong)
print(irisLong)
head(irisLong)
```
