---
title: "Homework 8"
format: html
---

# Homework 8
# 3.4.26

# For loops and randomizaton tests
# null-no diff (h0)
# H1 is diff

# randomization tests lecture #21
# use sample to shuffle
# 'read in data' use as backbone

```{r}
library(ggplot2)
set.seed(1000)
```


# 1
```{r}
times <- 100
n_vec <- sample(0:2, 100, replace = TRUE)

n_sum <- function(n_vec){
  counter <- 0
  for (i in 1:times){
    if(n_vec[i] == 0){
      counter <- counter + 1 
    }
  }
  return(counter) 
}

n_sum(n_vec)
```


# 2
```{r}
sum_zero <- sum(n_vec == 0)
print(sum_zero)
```

# 3
```{r}
mat_func <- function(row=6, col=3){
  mat <- matrix(nrow=row, ncol = col)
  for (i in 1:row){
    for (j in 1:col) {
      mat[i,j] <-j*i
  
    }
  
  }
  return(mat)
} 

mat_func()
```

# 4
# a
```{r}
group1 <- 2
group2 <- 7
group3 <- 10

groups <- c(rep("group1",2), rep("group2", 7), rep("group3", 10))
print(groups)

z <- c(runif(2) + 1, runif(7) + 6, + runif(10) + 14)
print(z)

df <- data.frame(grouping = groups, res=z)
print(df)

obs_means <- tapply(df$res,df$grouping,mean)
print(obs_means)
```

# b
```{r}
shuffle <- function()

read_data <- function(z=NULL) {

  if(is.null(z)){
    x_obs <- 1:20
    y_obs <- x_obs + 10*rnorm(20)
    df <- data.frame(x_obs, y_obs)
  } 
  else { 
    df <-read.table(file=z, header=TRUE, sep=",")}

return(df)
}
```